const paragraphs = [
    `His mother and father live in a flat in London. His father works in an insurance company, and his mother is a nurse. She works for the National Health Service. Shawn shares a flat with two friends and works in a restaurant. He's a waiter. He has two sisters, Lucy and Millie, who live together in Southampton.`,

    `Shawn's girlfriend's name is Maria, and she's Italian. She moved to the UK to study English a few years ago, and then stayed. She works in a café near Piccadilly Circus.Shawn's in love with Maria, and he also really likes her dog. He loves going for long walks in the park with Maria and her dog.`,


    `Yesterday I got up at 8:30 in the morning. After I made some coffee, I got dressed and went to the bank because I had to pay the rent. The bank is only a couple blocks away, so I got there in a few minutes. There wasn't a long line when I got in, so I paid the rent and left. Afterwards I went to the butcher's to get some meat. I also stopped at the market to get some tomatoes. I wanted to make pasta. When I got home I wrote a couple of emails. `,

    `The deadliest virus in modern history, perhaps of all time, was the 1918 Spanish Flu. It killed about 20 to 50 million people worldwide, perhaps more. The total death toll is unknown because medical records were not kept in many areas. The pandemic hit during World War I and devastated military troops. In the United States, for instance, more servicemen were killed from the flu than from the war itself. The Spanish flu was fatal to a higher proportion of young adults than most flu viruses.`,


    `The pandemic started mildly, in the spring of 1918, but was followed by a much more severe wave in the fall of 1918. The war likely contributed to the devastating mortality numbers, as large outbreaks occurred in military forces living in close quarters. Poor nutrition and the unsanitary conditions of war camps had an effect.A third wave occurred in the winter and spring of 1919, and a fourth, smaller wave occurred in a few areas in spring 1920. Initial symptoms of the flu were typical: sore throat, headache, and fever.`,

    `The flu often progressed rapidly to cause severe pneumonia and sometimes hemorrhage in the lungs and mucus membranes. A characteristic feature of severe cases of the Spanish Flu was heliotrope cyanosis, where the patient's face turned blue from lack of oxygen in the cells. Death usually followed within hours or days.Modern medicine such as vaccines, antivirals, and antibiotics for secondary infections were not available at that time, so medical personnel couldn't do much more than try to relieve symptoms.`,

    `It goes without saying that humans (mammals identifiable as those that stand upright and are comparatively advanced and capable of detailed thought) have pretty remarkable bodies, given all that they've accomplished. (Furthermore, an especially intelligent human brain produced this text!) To be sure, humans have overcome predators, disease, and all sorts of other obstacles over thousands of years. To fully understand and appreciate these accomplishments, let's take at some of the most well-known parts of the human body!`,

    `The head, or the spherical body part that contains the brain and rests at the top of the human body, has quite a few individual organs and body parts on it. (It should quickly be mentioned that hair occupies the space on top of the head, and the ears, the organs responsible for hearing, are located on either side of the head.) From top to bottom, the eyebrows, or horizontal strips of hair that can be found above the eye, are the first components of the head. The eyes are below them, and are round, orb-like organs that allow humans to see.`,

    `The eyes make way for the nose, or an external (sticking-out) organ that plays an important part in the breathing and bacteria-elimination processes. Below that is the mouth, or a wide, cavernous organ that chews food, removes bacteria, helps with breathing, and more. The mouth contains teeth, or small, white-colored, pointed body parts used to chew food, and the tongue, or a red-colored, boneless organ used to chew food and speak.`,

    `The legs are the long, muscular body parts that allow humans to move from one spot to another and perform a variety of actions. Each leg contains a thigh (a thick, especially muscular body part used to perform strenuous motions; the upper part of the leg) and a calf (thinner, more flexible body part that absorbs the shock associated with movement; the lower part of the leg). Feet can be found at the bottom of legs, and each foot is comprised of five toes, or small appendages that help balance.`,

    `Arms are long, powerful body parts that are located on either side of chest, below the shoulders;arms are comprised of biceps (the thicker, more powerful upper portion), and forearms (the thinner, more flexible lower portion). Hands, or small, gripping body parts used for a tremendous number of actions, are at the end of arms. Each hand contains five fingers, or small appendages used to grip objects. The aforementioned shoulders are rounded body parts that aid arms' flexibility. One's back is found on the opposite side of the stomach, and is a flat section of the body that contains important muscles that're intended to protect the lungs and other internal organs, in addition to helping humans perform certain motions and actions.`,

    `In June, Diane visited her friends who live in San Francisco, California. This was Diane's first time in the city, and she enjoyed her opportunities to walk around and explore. On the first day of her trip, Diane visited the Golden Gate Bridge. This red suspension bridge measures 1.7 miles in length. Diane and her friends did not walk across the bridge. However, they viewed it from the Golden Gate National Recreation Area, which offers hiking trails, picnicking areas, and presents spectacular views of the bridge and city. Diane and her friends made sure to take a group photograph here, featuring the bridge in the background.`,

    `The next day, Diane and her friends visited Alcatraz Island. This island is located 1.25 miles offshore in the San Francisco Bay. It used to serve as a lighthouse, military fort, and prison. Diane and her friends took a small tour boat across bay to reach the island. Their visit included a guided tour through the old military base and prison. They also took a walk around the island to appreciate some of the native wildlife in addition to the views of the city.`,

    `For most, spring is a time of "thawing," when the cold and snow of the winter are replaced by sunshine, reasonable temperatures, green grass, and more. It is also the season wherein previously dormant bees and butterflies reemerge, and when birds become more active. Summer follows spring and spans from about 21 June to 22 September, in America. Summer is the warmest, the longest, and (arguably) the liveliest of the four seasons; students from kindergarten to college are given two or so summer months off from class, and to be sure, there are more young individuals out and about during this season than any other. It's not uncommon to see shorts, t-shirts, and sunglasses worn by those who're soaking up the summer's hot sun, and to stay cool, many individuals crank the air conditioning, take a dip in a swimming pool, and/or explore the ever-comforting ocean waves.`,

    `The four seasons
    The four seasons are spring, summer, fall, and winter, and although various areas of the United States experience drastically different weather during these times, all portions of the country recognize the seasons; winter in California may bring heat, and winter in New York may bring blizzards, but both periods are nevertheless winter.`,
    
    `Following winter, spring begins on 20 March and ends on either 20 June or 21 June, in the United States (this date may vary slightly from year to year and hemisphere to hemisphere). For most, spring is a time of "thawing," when the cold and snow of the winter are replaced by sunshine, reasonable temperatures, green grass, and more. It is also the season wherein previously dormant bees and butterflies reemerge, and when birds become more active.`,
    
    `Summer follows spring and spans from about 21 June to 22 September, in America. Summer is the warmest, the longest, and (arguably) the liveliest of the four seasons; students from kindergarten to college are given two or so summer months off from class, and to be sure, there are more young individuals out and about during this season than any other. It's not uncommon to see shorts, t-shirts, and sunglasses worn by those who're soaking up the summer's hot sun, and to stay cool, many individuals crank the air conditioning, take a dip in a swimming pool, and/or explore the ever-comforting ocean waves.`,
    
    `Autumn (or fall), more than being a simple precursor to winter, is one of the most beautiful and exciting seasons. Spanning from 22 September to 21 December (technically, that is; snow will begin to fall long before this latter date, in most parts of the country, leading many to classify the period as winter) in the US, autumn is characterized by falling leaves, Halloween (on 31 October), and Thanksgiving. During fall, traditional farmers harvest their produce, and the aforementioned falling leaves change to gorgeous orange, red, and yellow colors; these colors are generally associated with autumn itself, in turn. In the US, winter spans from 21 December to 20 March, and is, as one would expect, the coldest of the four seasons.`,



]